### ISSUE TITLE
Add ability for relative paths

### ISSUE THREAD

**Issue by sc0rp10** [Pavliko/postcss-svg#12]
Now option path is required. But if plugin will be open svg files by their relative path (relative to postcss-file), it's may be not required.

```
.foo {
    background-image: svg("logo");  /* file logo.svg is located in same folder with stylesheet */
    /* or */ 
    background-image: svg("../svg/logo");
}
```

And got ENOENT error

**Comment by olebedev** [comment]
Hi @sc0rp10, I have just fixed it [here](https://github.com/olebedev/postcss-svg).

**Comment by cmnstmntmn** [comment]
i still get the same error, even with latest version installed.

tree and `menu.css` content
<img width="746" alt="screen shot 2016-04-22 at 18 10 44" src="https://cloud.githubusercontent.com/assets/2312755/14745791/96ace4aa-08b5-11e6-8351-b00deef3ca17.png">

do i miss something ?

**Comment by sc0rp10** [comment]
@cmnstmntmn what error? did you miss with comment?

**Comment by cmnstmntmn** [comment]
`Error: ENOENT: no such file or directory, open 'arrow.svg'`

**Comment by cmnstmntmn** [comment]
the problem is that i cannot use my custom svgs. the only way i can make it work, is using evil icons

`background-image: svg("ei#sc-github", "[fill]: black");`

while `background-image: svg("../my_path/arrow");` fail to compile and throws

`Error: ENOENT: no such file or directory, open 'arrow.svg'`

**Comment by sc0rp10** [comment]
@cmnstmntmn you don't know how to use github? how associated your error and my issue?

**Comment by sbstnmsch-zz** [comment]
Come on ppl, behave, this is Open Source! @cmnstmntmn did u setup your SVGs path like? This works for me:

```
_postcssSvgProcessor = require('postcss-svg')({
      paths: ['src/images'],
      ei: { "defaults": "[fill]: white" }
    }),
```

and in CSS:

```
.icon-needle {
  background-image: svg("needle");
}
```

**Comment by cmnstmntmn** [comment]
@sbstnmsch thank you, forgot about them

**Comment by jonathantneal** [comment]
Relative paths work in v2, if they didn’t already work before. You can also pass in your own paths to lookup.
